language: python
python:
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4
env:
- WITH_OPTIONS=true
- WITH_OPTIONS=false
before_install:
- sudo apt-get update
- sudo locale-gen de_DE.UTF-8
- sudo apt-get install bc
install:
- if [[ $WITH_OPTIONS == true ]]; then sudo apt-get install libicu-dev; fi
- if [[ $WITH_OPTIONS == true ]]; then pip install fastnumbers; fi
- if [[ $WITH_OPTIONS == true ]]; then pip install PyICU; fi
- if [[ 1 -eq $(echo "$TRAVIS_PYTHON_VERSION < 3.4" | bc -l) ]]; then pip install pathlib; fi
- if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install argparse; fi
- if [[ $(echo "$TRAVIS_PYTHON_VERSION < 3.3" | bc -l) ]]; then pip install mock; fi
- pip install pytest-cov pytest-flakes pytest-pep8 hypothesis
- pip install coveralls
script:
- python -m pytest --cov natsort --flakes --pep8
- python -m pytest --doctest-modules natsort
- python -m pytest README.rst docs/source/intro.rst docs/source/examples.rst
after_success:
  coveralls
