language: python
python:
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4
install:
- pip install pytest-cov pytest-flakes pytest-pep8
- pip install coveralls
- if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install argparse; fi
script:
- python -m pytest --cov natsort --flakes --pep8
- python -m pytest --doctest-modules natsort
- python -m pytest README.rst docs/source/intro.rst docs/source/examples.rst
- python -m pytest test_natsort/stress_natsort.py
after_success:
  coveralls
before_deploy:
- pip install Sphinx numpydoc # Only needed to install for deploying
- python setup.py build_sphinx
deploy:
  provider: pypi
  user: SethMMorton
  password:
    secure: OaYQtVh4mGT0ozN7Ar2lSm2IEVMKIyvOESGPGLwVyVxPqp6oC101MovJ7041bZdjMzirMs54EJwtEGQpKFmDBGcKgbjPiYId5Nqb/yDhLC/ojgarbLoFJvUKV6dWJePyY7EOycrqcMdiDabdG80Bw4zziQExbmIOdUiscsAVVmA=
  on:
    tags: true
    repo: SethMMorton/natsort
  distributions: "sdist bdist_wheel"
  docs_dir: build/sphinx/html
